### ISSUE TITLE
Handle outputting a Metaplex Edition

### ISSUE THREAD

**Issue by tomjohn1028** [RohanKapurDEV/fusion#4]
- [x] add Metaplex Token Metadata contract to the repository and deployment at test genesis
- [x] Write test(s) for the `CreateFormula` instruction that validates a formula's output can be a Metaplex Edition
- [x] update `CreateFormula` to handle transferring Edition mint capabilities to the protocol and pass tests
- [x] write test(s) for the `Craft` instruction that takes in x SPL Token `Ingredients` and expects an output to be a new Edition print
- [x] update `Craft` to mint a new output edition

**Comment by RohanKapurDEV** [comment]
Task 1 addressed by 3e6e843c4ce62a18e698c4ce6937184c2cfa1568 and 4fcd44ed1110a7047630a7eafc60152e178b9b9c
Created `metaplex-edition` branch for task 2

**Comment by tomjohn1028** [comment]
@RohanKapurDEV I added some helpers to the test setup for adding meta data to a mint and then creating a master edition from it. I'm a little stuck on figuring out exactly what needs to be transferred to the program so that the program will be able to properly call [_mint_new_edition_from_master_edition_via_token_](https://docs.rs/spl-token-metadata/0.0.1/spl_token_metadata/instruction/fn.mint_new_edition_from_master_edition_via_token.html).

**Comment by RohanKapurDEV** [comment]
There seem to be some helpful comments [here](https://github.com/metaplex-foundation/metaplex/blob/master/rust/token-metadata/program/src/instruction.rs#L191). Not 100% sure that's what we're looking for but I'm gonna go through the helper functions and try calling them with that info

**Comment by tomjohn1028** [comment]
@RohanKapurDEV 

Here's an example of a non-anchor CPI (unsigned) https://github.com/mithraiclabs/psyoptions/blob/master/programs/psy_american/src/lib.rs#L356

If you need to sign you would use [invoke_signed](https://docs.rs/solana-program/1.7.14/solana_program/program/fn.invoke_signed.html), here's an example of that: https://github.com/mithraiclabs/psyoptions/blob/master/programs/cpi_examples/src/lib.rs#L300

I'm certain this case would require signing with a PDA that owns the TokenAccount holding the master edition mint token. 

So in my mind the `CreateFormula` instruction needs to do the following
1. Check if the output mint is a MasterEdition
    * If it is, then there should be another 2 accounts in remaining accounts. 1) The TokenAccount holding the current MasterEdition token. 2) The AccountInfo for the PDA of the new TokenAccount that will hold the MasterEdition for the program
2. Extract the two additional accounts
3. CPI to SPL Token program to create and init a new SPL TokenAccount with the PDA account
4. CPI to SPL Token program to transfer the MasterEdition to the new SPL Token account

**Comment by RohanKapurDEV** [comment]
Initial draft of behaviour at b162ac698811eef2ba3a0d9ab831a7094beec76a and 163f7118cc450f57d1a051707587052df9d91aa8.

**Comment by RohanKapurDEV** [comment]
Will begin work on calling `mint_new_edition_from_master_edition_via_token` from `craft` ix when output items are MasterEditions via non-anchor CPI calls to token-metadata contract. Will update here.

**Comment by tomjohn1028** [comment]
The `Craft` on this one is interesting to think about. When printing a new edition, new Mint and TokenAccount accounts are required. So if the user wanted to allow printing 3 output prints, then there's a need to have 6 additional accounts.

The steps to setup accounts needed for a mint new edition from master edition can be found by stepping through code [here](https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/web/src/actions/setupMintEditionIntoWalletInstructions.ts#L39)

**Comment by tomjohn1028** [comment]
I got a happy path print working. There are some optimizations that can be made to reduce the transaction size and get the tests to pass again though.
